#! /bin/bash

docker kill kamon-grafana-dashboard
docker rm kamon-grafana-dashboard

docker run -d -v /etc/localtime:/etc/localtime:ro -p 80:80 -p 8125:8125/udp -p 8126:8126 --name kamon-grafana-dashboard kamon/grafana_graphite
